title: Cayman Blog Theme
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.
show_downloads: true

baseurl: "/docs" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://telegram-zh.github.io" # change this to the base hostname & protocol for your site
permalink: /:title.html

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
#  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

#header_page_refs: ['now', 'about', 'contact']
header_page_refs: [{'id' : 'telegram', 'name': '电报'}, {'id': 'twitter', 'name': '推特'}, {'id': 'exchange', 'name': '交易所'}, {'id': 'account', 'name': '账号类'}]
