title: 软件翻译官
description: 
show_downloads: true

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://tggsearch.github.io" # change this to the base hostname & protocol for your site


google_analytics: G-61CEYEJKCR

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
 # date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: 软件翻译官
image: /thumbnail-jumbo.png
twitter:
  username: idanhua

plugins:
  - jekyll-target-blank
  - jekyll-paginate

target-blank:
    rel: nofollow

# Paginate
paginate: 10

#header_page_refs: [{'id' : 'telegram', 'name': '电报'}, {'id': 'twitter', 'name': '推特'}, {'id': 'exchange', 'name': '交易所'}, {'id': 'account', 'name': '账号类'}]
header_page_refs: ['now', 'about', 'contact']